openapi: 3.0.0
info:
  title: "Votre API"
  description: "Description de votre API."
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/api/v1"
paths:
  /clients:
    get:
      summary: "Lister ensemble des clients"
      responses:
        '200':
          description: "Liste des clients"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      type: object
                    example: [{"id": 1, "surname": "Doe", "telephone": "771223122"}]
                  message:
                    type: string
                    example: "Liste des clients"
